"""Bloqueio de IP por força bruta: falhas de login e IPs bloqueados.

RLS ligado sem políticas, como nas demais tabelas no Supabase: a API pública do
Supabase (chave anônima) não lê nada; só o backend, que conecta direto no banco.

Revision ID: d4e5f6a7b8c9
Revises: c3e4f5a6b7d8
Create Date: 2026-10-06 13:20:42.208760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, None] = 'c3e4f5a6b7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('falha_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_falha_login'))
    )
    op.create_index('ix_falha_login_ip_criado_em', 'falha_login', ['ip', 'criado_em'], unique=False)
    op.create_table('ip_bloqueado',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('bloqueado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ip', name=op.f('pk_ip_bloqueado'))
    )
    # ### end Alembic commands ###
    op.execute("ALTER TABLE falha_login ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ip_bloqueado ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_bloqueado')
    op.drop_index('ix_falha_login_ip_criado_em', table_name='falha_login')
    op.drop_table('falha_login')
    # ### end Alembic commands ###
